version: '3.8'

services:
  # nginx 웹서버 공식 이미지
  # 유입된 요청을 확인해 PHP 컨테이너로 전달하는 역할
  # nginx 구성 커스텀을 반영하기 위해서는 바인드 마운트 필요
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # php는 로컬을 통해서가 아닌 웹서버와 직접적으로 통신한다.
  php:
    # php 공식 이미지를 기반으로 확장 프로그램을 가진 커스텀 이미지 생성
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile

    # PHP 인터프리터는 소스코드에 접근 가능해야 한다.
    # delegated -> 안전성은 떨어지나 속도가 향상되는 최적화 옵션
    # 읽기와 쓰기 모두 일어나기에 ro 옵션은 부여하지 않는다.
    volumes:
      - ./src:/var/www/html:delegated

  # mysql 공식 이미지
  # 구동에 필요한 환경변수 설정이 필요하다.
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  # composer:
  # artisan:
  # npm:
