version: '3.8'

services:
  # nginx 웹서버 -> 메인 엔트리포인트
  # 유입된 요청을 확인해 PHP 컨테이너로 전달하는 역할
  # php 파일에 대한 요청만으로 포워딩하기 때문에 소스 코드가 필요하다.
  # nginx 구성 커스텀을 반영하기 위해서는 바인드 마운트 필요
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # nginx 커스텀 구성을 더 넓은 구성에 병합
    # 단 하나의 최상위 서비스명으로 모든 CASCADE된 서비스 차례로 구동하기
    depends_on:
      - php
      - mysql

  # php는 로컬을 통해서가 아닌 웹서버와 직접적으로 통신한다.
  # php는 소스 코드를 통해 간접적으로 데이터베이스와 통신한다.
  php:
    # php 공식 이미지를 기반으로 확장 프로그램을 가진 커스텀 이미지 생성
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile

    # PHP 인터프리터는 소스코드에 접근 가능해야 한다.
    # delegated -> 안전성은 떨어지나 속도가 향상되는 최적화 옵션
    # 읽기와 쓰기 모두 일어나기에 ro 옵션은 부여하지 않는다.
    volumes:
      - ./src:/var/www/html:delegated

  # mysql 공식 이미지
  # 구동에 필요한 환경변수 설정이 필요하다.
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  # 라라벨 프레임워크를 위한 PHP로 작성된 PHP의 종속성 관리 도구
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile

    # composer 컨테이너로 라라벨 애플리케이션을 생성하면 로컬 머신의 소스 폴더로 미러링
    volumes:
      - ./src:/var/www/html

  # artisan:
  # npm:
